### ISSUE TITLE
"unknown type %.*s" when attempting to use the ljsyscall lib

### ISSUE THREAD

**Issue by ayourtch** [jmckaskill/luaffi#1]
I tried the luaffi (thanks for the work, btw!) and stumbled upon this problem.

To reproduce:

wget https://raw.github.com/justincormack/ljsyscall/master/syscall.lua

lua -e 'require "syscall"'

This gives:

lua: ./syscall.lua:1555: unknown type %.*s on line 6
stack traceback:
        [C]: in function '?'
        ./syscall.lua:1555: in main chunk
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: ?

**Comment by jmckaskill** [comment]
The error message is fixed in 403cda56a21b18ea963c.
The error is due to the use of static const int, which is on my todo list at some point. The suggestion atm is to use enum for constants (this is actually more in line with C code anyways...)

**Comment by ayourtch** [comment]
Thanks a lot for the reply and detailed description!
