### ISSUE TITLE
msvcbuild.bat LUA_EXE quoting

### ISSUE THREAD

**Issue by daurnimator** [jmckaskill/luaffi#2]
msvcbuild.bat is inconsistent in it's quoting; 

@set LUA_INCLUDE=C:\Program Files (x86)\Lua\5.1\include
@set LUA_LIB=C:\Program Files (x86)\Lua\5.1\lib\lua5.1.lib
@set LUA_EXE="C:\Program Files (x86)\Lua\5.1\lua.exe"
@set LUA_DLL=C:\Program Files (x86)\Lua\5.1\lua5.1.dll

LUA_EXE needs quotes if it contains a space; the others don't work with quotes.

**Comment by jmckaskill** [comment]
Thanks I've added a comment indicating that none of those should be quoted and quoted the LUA_EXE at the place its used instead.

**Comment by daurnimator** [comment]
You also need to fix it for tests:
@if "%1"=="test" %LUA_EXE% test.lua
@if "%1"=="test-5.2" %LUA_EXE% test.lua
@if "%1"=="test-release" %LUA_EXE% test.lua

**Comment by jmckaskill** [comment]
Done, thanks.
