### ISSUE TITLE
Memory leak with 5.2

### ISSUE THREAD

**Issue by jmckaskill** [jmckaskill/luaffi#24]
The greyscale test on http://luajit.org/ext_ffi.html seems to be leaking with 5.2, but not with 5.1.

**Comment by jamesgraves** [comment]
I believe this is a bug with Lua 5.2.0, which seems to be fixed with the 5.2.1-rc1.  I re-ran the program with 5.2.1-rc1 and the memory usage stayed steady throughout the run, without needing to call collectgarbage().
