### ISSUE TITLE
S.open in ljsyscall

### ISSUE THREAD

**Issue by jmckaskill** [jmckaskill/luaffi#28]
lua: unable to convert argument 2 from cdata<int> to cdata<int64_t>

**Comment by jmckaskill** [comment]
```
lua: unable to convert argument 2 from cdata<int> to cdata<int64_t>
stack traceback:
   [C]: in function 'open'
    ./io/syscall.lua:2388: in function 'open'
```

**Comment by justincormack** [comment]
Minimal test case (I wrote ljsyscall, happy to get it to work with luaffi)

``` lua

local ffi = require "ffi"

local C = ffi.C

ffi.cdef[[
typedef uint32_t mode_t;
int open(const char *pathname, int flags, mode_t mode);
]]

local int_t = ffi.typeof("int")

assert(ffi.C.open("/tmp/file/does/not/exist", int_t(1), 0))
```

**Comment by justincormack** [comment]
note I fixed this issue in ljsyscall, although it seems to be a bug. Working on other issues.

**Comment by jmckaskill** [comment]
Ah I see what's happening. I was wondering how he had managed to create a cdata<int> because any access to an int is normally converted to a lua number.
