### ISSUE TITLE
ffi.cdef doesn't understand/skip __attribute__

### ISSUE THREAD

**Issue by daurnimator** [jmckaskill/luaffi#4]
Unlike the luajit ffi; ffi.cdef doesn't understand or skip `__attribute__`

eg:
`ffi = require"ffi"
ffi.cdef [[
    typedef int ALenum;
    __attribute__((dllimport)) void __attribute__((__cdecl__)) alEnable( ALenum capability );
]]`
error: `unknown type __attribute__ on line 2`

**Comment by jmckaskill** [comment]
This should now be fixed.
