### ISSUE TITLE
casting between numbers and pointers

### ISSUE THREAD

**Issue by justincormack** [jmckaskill/luaffi#41]
in luajit the ffi can cast numbers to and from pointers.

eg S.cast("char *", 1) gives a pointer to memory location 1
and I can use
ffi.cast("long", ret) == -1
to test the return value from mmap.

I can't work out how to do either of those with luaffi, so I can't get mmap to work for ljsyscall.

**Comment by jmckaskill** [comment]
You should be able to cast via uintptr_t for the moment, but the cast rules are indeed a bit strict atm.

```
ffi.cast('long', ffi.cast('uintptr_t', ret))
```

**Comment by jmckaskill** [comment]
Hmm does (long) ptr even work on 64bit systems where long is 32 bit (e.g. win64)?

**Comment by justincormack** [comment]
this code only runs on Linux...

**Comment by jmckaskill** [comment]
Oh I realize that, I'm just wondering about the validity of allowing ffi.cast('int', ptr) in the general case. It seems that msvc doesn't mind (int) ptr so I'll just chop the pointer if the target int type is smaller.
