### ISSUE TITLE
Add support for __new metamethod

### ISSUE THREAD

**Issue by jmckaskill** [jmckaskill/luaffi#48]

**Comment by justincormack** [comment]
Started using this method and it cleans up a lot of stuff...

**Comment by justincormack** [comment]
I think this might be the only thing stopping ljsyscall working with luaffi again - fixed most of the other issues... will take a look as it should not be too hard to do.

**Comment by justincormack** [comment]
This can be closed now.

**Comment by jmckaskill** [comment]
Thanks
