### ISSUE TITLE
compiling error in  windows xp sp2 and fixed.

### ISSUE THREAD

**Issue by guixue** [jmckaskill/luaffi#55]
while I am compiling the  ffi.dll under vs2005 promt line.
error just like:

ffi.c(2962) : error C2220: 警告被视为错误 - 没有生成“object”文件
ffi.c(2962) : warning C4013: “GetModuleHandleExA”未定义；假设外部返回 int
ffi.c(2962) : error C2065: “GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS”: 未声明的标
识符

fix solution:

add the line to  the block: #ifdef _WIN32.
# define _WIN32_WINNT 0x0501

at the beginning of ffi.h,

**Comment by jmckaskill** [comment]
Can you create a pull request please.

**Comment by guixue** [comment]
more the to the pull #56 . please help to review, thanks very much.
