### ISSUE TITLE
I can't seem to set enum values

### ISSUE THREAD

**Issue by daurnimator** [jmckaskill/luaffi#9]
Setting enums in a struct doesn't seem to work;
Same error if you do it in the constructor; or afterwards.

A test case:

```
ffi = require"ffi"

ffi.cdef [[
    typedef enum {
    foo,
    } an_enum;

    typedef struct {
    an_enum x;
    } a_struct;
]]

local new = ffi.typeof ( "a_struct" )
new(ffi.C.foo)
```

ERROR:
    lua: unable to convert argument 2 from lua<number> to cdata<struct 2>

**Comment by jmckaskill** [comment]
Thanks for the report. I thought I had an enum test in the test suite.... but apparently not.
